#!/usr/bin/env python3

import sys

af = open(sys.argv[1], "rb")
bf = open(sys.argv[2], "rb")

a = af.read()
b = bf.read()

assert len(a) == len(b)
for i, (A, B) in enumerate(zip(a, b)):
    if A != B:
      print('\n@', i, A,B, end="")
